# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'placement.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 1000)
        MainWindow.setStyleSheet("\n"
"/* === STYLE GLOBAL === */\n"
"QMainWindow {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"                                stop:0 #E3F2FD, stop:0.5 #BBDEFB, stop:1 #90CAF9);\n"
"    font-family: \'Segoe UI\', \'Roboto\', \'Arial\', sans-serif;\n"
"}\n"
"\n"
"/* === GROUPBOX === */\n"
"QGroupBox {\n"
"    font-size: 14pt;\n"
"    font-weight: bold;\n"
"    border: 2px solid #1976D2;\n"
"    border-radius: 15px;\n"
"    margin-top: 20px;\n"
"    padding: 20px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                stop:0 #FFFFFF, stop:1 #F5F5F5);\n"
"    color: #1565C0;\n"
"}\n"
"\n"
"QGroupBox::title {\n"
"    subcontrol-origin: margin;\n"
"    subcontrol-position: top left;\n"
"    padding: 5px 15px;\n"
"    background-color: #1976D2;\n"
"    color: white;\n"
"    border-radius: 8px;\n"
"    margin-left: 10px;\n"
"}\n"
"\n"
"/* === BOUTONS === */\n"
"QPushButton {\n"
"    background-color: #42A5F5;\n"
"    border: 1px solid #1976D2;\n"
"    border-radius: 6px;\n"
"    padding: 6px 15px;\n"
"    color: white;\n"
"    font-weight: normal;\n"
"    font-size: 10pt;\n"
"    min-height: 28px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #64B5F6;\n"
"    border: 1px solid #0D47A1;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1976D2;\n"
"}\n"
"\n"
"QPushButton#btnOptimize {\n"
"    background-color: #66BB6A;\n"
"    border: 1px solid #43A047;\n"
"    font-size: 11pt;\n"
"    font-weight: bold;\n"
"    min-height: 40px;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"QPushButton#btnOptimize:hover {\n"
"    background-color: #81C784;\n"
"    border: 1px solid #2E7D32;\n"
"}\n"
"\n"
"QPushButton#btnAddSite, QPushButton#btnAddZone {\n"
"    background-color: #66BB6A;\n"
"    border: 1px solid #43A047;\n"
"}\n"
"\n"
"QPushButton#btnAddSite:hover, QPushButton#btnAddZone:hover {\n"
"    background-color: #81C784;\n"
"}\n"
"\n"
"QPushButton#btnRemoveSite, QPushButton#btnRemoveZone {\n"
"    background-color: #EF5350;\n"
"    border: 1px solid #E53935;\n"
"}\n"
"\n"
"QPushButton#btnRemoveSite:hover, QPushButton#btnRemoveZone:hover {\n"
"    background-color: #F44336;\n"
"}\n"
"\n"
"/* === TABLEAUX === */\n"
"QTableWidget {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #90CAF9;\n"
"    border-radius: 10px;\n"
"    gridline-color: #E1F5FE;\n"
"    selection-background-color: #64B5F6;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QTableWidget::item {\n"
"    padding: 8px;\n"
"}\n"
"\n"
"QTableWidget::item:selected {\n"
"    background-color: #42A5F5;\n"
"    color: white;\n"
"}\n"
"\n"
"QTableWidget::item:alternate {\n"
"    background-color: #E3F2FD;\n"
"}\n"
"\n"
"QHeaderView::section {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                stop:0 #1976D2, stop:1 #1565C0);\n"
"    color: white;\n"
"    padding: 10px;\n"
"    border: 1px solid #0D47A1;\n"
"    font-weight: bold;\n"
"    font-size: 10pt;\n"
"}\n"
"\n"
"QHeaderView::section:hover {\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1,\n"
"                                stop:0 #2196F3, stop:1 #1976D2);\n"
"}\n"
"\n"
"/* === LABELS === */\n"
"QLabel {\n"
"    font-size: 11pt;\n"
"    color: #263238;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"/* === COMBOBOX === */\n"
"QComboBox {\n"
"    border: 2px solid #90CAF9;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    background-color: white;\n"
"    font-size: 10pt;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 2px solid #42A5F5;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: none;\n"
"    width: 30px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #90CAF9;\n"
"    selection-background-color: #42A5F5;\n"
"    background-color: white;\n"
"}\n"
"\n"
"/* === SPINBOX === */\n"
"QSpinBox, QDoubleSpinBox {\n"
"    border: 2px solid #90CAF9;\n"
"    border-radius: 8px;\n"
"    padding: 8px;\n"
"    background-color: white;\n"
"    font-size: 10pt;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QSpinBox:hover, QDoubleSpinBox:hover {\n"
"    border: 2px solid #42A5F5;\n"
"}\n"
"\n"
"QSpinBox:focus, QDoubleSpinBox:focus {\n"
"    border: 2px solid #1976D2;\n"
"}\n"
"\n"
"/* === ZONE DE TEXTE === */\n"
"QTextEdit {\n"
"    background-color: #FFFFFF;\n"
"    border: 2px solid #90CAF9;\n"
"    border-radius: 10px;\n"
"    padding: 15px;\n"
"    font-family: \'Consolas\', \'Monaco\', monospace;\n"
"    font-size: 10pt;\n"
"    color: #263238;\n"
"}\n"
"\n"
"/* === SCROLLBAR === */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: #E3F2FD;\n"
"    width: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: #90CAF9;\n"
"    border-radius: 6px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: #64B5F6;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #E3F2FD;\n"
"    height: 12px;\n"
"    border-radius: 6px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    background: #90CAF9;\n"
"    border-radius: 6px;\n"
"    min-width: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    background: #64B5F6;\n"
"}\n"
"    ")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(0, 0, 0, 0)
        self.mainLayout.setSpacing(0)
        self.mainLayout.setObjectName("mainLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setStyleSheet("\n"
"        QScrollArea {\n"
"         border: none;\n"
"         background: transparent;\n"
"        }\n"
"       ")
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_main = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_main.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_main.setSpacing(15)
        self.verticalLayout_main.setObjectName("verticalLayout_main")
        self.labelTitle = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.labelTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.labelTitle.setStyleSheet("\n"
"        font-size: 20pt;\n"
"        font-weight: bold;\n"
"        color: #0D47A1;\n"
"        padding: 15px;\n"
"        background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                                    stop:0 #FFFFFF, stop:0.5 #E3F2FD, stop:1 #FFFFFF);\n"
"        border-radius: 15px;\n"
"        border: 2px solid #1976D2;\n"
"       ")
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout_main.addWidget(self.labelTitle)
        self.groupSites = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupSites.setObjectName("groupSites")
        self.verticalLayout_sites = QtWidgets.QVBoxLayout(self.groupSites)
        self.verticalLayout_sites.setObjectName("verticalLayout_sites")
        self.tableSites = QtWidgets.QTableWidget(self.groupSites)
        self.tableSites.setMinimumHeight(250)
        self.tableSites.setMaximumHeight(400)
        self.tableSites.setAlternatingRowColors(True)
        self.tableSites.setObjectName("tableSites")
        self.tableSites.setColumnCount(4)
        self.tableSites.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableSites.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSites.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSites.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableSites.setHorizontalHeaderItem(3, item)
        self.verticalLayout_sites.addWidget(self.tableSites)
        self.layout_buttons_sites = QtWidgets.QHBoxLayout()
        self.layout_buttons_sites.setObjectName("layout_buttons_sites")
        self.btnAddSite = QtWidgets.QPushButton(self.groupSites)
        self.btnAddSite.setObjectName("btnAddSite")
        self.layout_buttons_sites.addWidget(self.btnAddSite)
        self.btnRemoveSite = QtWidgets.QPushButton(self.groupSites)
        self.btnRemoveSite.setObjectName("btnRemoveSite")
        self.layout_buttons_sites.addWidget(self.btnRemoveSite)
        self.verticalLayout_sites.addLayout(self.layout_buttons_sites)
        self.verticalLayout_main.addWidget(self.groupSites)
        self.groupZones = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupZones.setObjectName("groupZones")
        self.verticalLayout_zones = QtWidgets.QVBoxLayout(self.groupZones)
        self.verticalLayout_zones.setObjectName("verticalLayout_zones")
        self.tableZones = QtWidgets.QTableWidget(self.groupZones)
        self.tableZones.setMinimumHeight(250)
        self.tableZones.setMaximumHeight(400)
        self.tableZones.setAlternatingRowColors(True)
        self.tableZones.setObjectName("tableZones")
        self.tableZones.setColumnCount(5)
        self.tableZones.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableZones.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZones.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZones.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZones.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableZones.setHorizontalHeaderItem(4, item)
        self.verticalLayout_zones.addWidget(self.tableZones)
        self.layout_buttons_zones = QtWidgets.QHBoxLayout()
        self.layout_buttons_zones.setObjectName("layout_buttons_zones")
        self.btnAddZone = QtWidgets.QPushButton(self.groupZones)
        self.btnAddZone.setObjectName("btnAddZone")
        self.layout_buttons_zones.addWidget(self.btnAddZone)
        self.btnRemoveZone = QtWidgets.QPushButton(self.groupZones)
        self.btnRemoveZone.setObjectName("btnRemoveZone")
        self.layout_buttons_zones.addWidget(self.btnRemoveZone)
        self.verticalLayout_zones.addLayout(self.layout_buttons_zones)
        self.verticalLayout_main.addWidget(self.groupZones)
        self.groupParameters = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupParameters.setObjectName("groupParameters")
        self.gridLayoutParameters = QtWidgets.QGridLayout(self.groupParameters)
        self.gridLayoutParameters.setHorizontalSpacing(20)
        self.gridLayoutParameters.setVerticalSpacing(15)
        self.gridLayoutParameters.setObjectName("gridLayoutParameters")
        self.labelMode = QtWidgets.QLabel(self.groupParameters)
        self.labelMode.setObjectName("labelMode")
        self.gridLayoutParameters.addWidget(self.labelMode, 0, 0, 1, 1)
        self.comboModeDecision = QtWidgets.QComboBox(self.groupParameters)
        self.comboModeDecision.setObjectName("comboModeDecision")
        self.comboModeDecision.addItem("")
        self.comboModeDecision.addItem("")
        self.gridLayoutParameters.addWidget(self.comboModeDecision, 0, 1, 1, 1)
        self.labelTotalAmb = QtWidgets.QLabel(self.groupParameters)
        self.labelTotalAmb.setObjectName("labelTotalAmb")
        self.gridLayoutParameters.addWidget(self.labelTotalAmb, 0, 2, 1, 1)
        self.spinTotalAmbulances = QtWidgets.QSpinBox(self.groupParameters)
        self.spinTotalAmbulances.setMinimum(1)
        self.spinTotalAmbulances.setMaximum(500)
        self.spinTotalAmbulances.setProperty("value", 5)
        self.spinTotalAmbulances.setObjectName("spinTotalAmbulances")
        self.gridLayoutParameters.addWidget(self.spinTotalAmbulances, 0, 3, 1, 1)
        self.labelMaxDist = QtWidgets.QLabel(self.groupParameters)
        self.labelMaxDist.setObjectName("labelMaxDist")
        self.gridLayoutParameters.addWidget(self.labelMaxDist, 1, 0, 1, 1)
        self.spinMaxDistance = QtWidgets.QDoubleSpinBox(self.groupParameters)
        self.spinMaxDistance.setMinimum(0.1)
        self.spinMaxDistance.setMaximum(10000.0)
        self.spinMaxDistance.setProperty("value", 5.0)
        self.spinMaxDistance.setDecimals(1)
        self.spinMaxDistance.setSingleStep(0.5)
        self.spinMaxDistance.setObjectName("spinMaxDistance")
        self.gridLayoutParameters.addWidget(self.spinMaxDistance, 1, 1, 1, 1)
        self.verticalLayout_main.addWidget(self.groupParameters)
        self.btnOptimize = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnOptimize.setObjectName("btnOptimize")
        self.verticalLayout_main.addWidget(self.btnOptimize)
        self.groupResults = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupResults.setObjectName("groupResults")
        self.verticalLayout_results = QtWidgets.QVBoxLayout(self.groupResults)
        self.verticalLayout_results.setObjectName("verticalLayout_results")
        self.textResults = QtWidgets.QTextEdit(self.groupResults)
        self.textResults.setMinimumHeight(300)
        self.textResults.setMaximumHeight(500)
        self.textResults.setReadOnly(True)
        self.textResults.setStyleSheet("\n"
"           QTextEdit {\n"
"            font-size: 10pt;\n"
"            line-height: 1.4;\n"
"           }\n"
"          ")
        self.textResults.setObjectName("textResults")
        self.verticalLayout_results.addWidget(self.textResults)
        self.verticalLayout_main.addWidget(self.groupResults)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.mainLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setStyleSheet("\n"
"     QStatusBar {\n"
"      background-color: #1976D2;\n"
"      color: white;\n"
"      font-weight: bold;\n"
"      padding: 5px;\n"
"     }\n"
"    ")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "🚑 Placement Optimal d\'Ambulances - Optimisation Intelligente"))
        self.labelTitle.setText(_translate("MainWindow", "🚑 Système d\'Optimisation de Placement d\'Ambulances"))
        self.groupSites.setTitle(_translate("MainWindow", "Sites Potentiels"))
        self.tableSites.setToolTip(_translate("MainWindow", "Liste des sites où les ambulances peuvent être installées"))
        item = self.tableSites.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nom du Site"))
        item = self.tableSites.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X (km)"))
        item = self.tableSites.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y (km)"))
        item = self.tableSites.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Capacité Max"))
        self.btnAddSite.setText(_translate("MainWindow", "Ajouter Site"))
        self.btnAddSite.setToolTip(_translate("MainWindow", "Ajouter un nouveau site"))
        self.btnRemoveSite.setText(_translate("MainWindow", "Supprimer Site"))
        self.btnRemoveSite.setToolTip(_translate("MainWindow", "Supprimer le site sélectionné"))
        self.groupZones.setTitle(_translate("MainWindow", "Zones à Couvrir"))
        self.tableZones.setToolTip(_translate("MainWindow", "Liste des zones à couvrir avec leur population"))
        item = self.tableZones.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Nom de la Zone"))
        item = self.tableZones.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "X (km)"))
        item = self.tableZones.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Y (km)"))
        item = self.tableZones.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Population"))
        item = self.tableZones.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Priorité"))
        self.btnAddZone.setText(_translate("MainWindow", "Ajouter Zone"))
        self.btnAddZone.setToolTip(_translate("MainWindow", "Ajouter une nouvelle zone"))
        self.btnRemoveZone.setText(_translate("MainWindow", "Supprimer Zone"))
        self.btnRemoveZone.setToolTip(_translate("MainWindow", "Supprimer la zone sélectionnée"))
        self.groupParameters.setTitle(_translate("MainWindow", "Paramètres du Modèle d\'Optimisation"))
        self.labelMode.setText(_translate("MainWindow", "Mode de Décision :"))
        self.labelMode.setToolTip(_translate("MainWindow", "Choisissez le type de variables de décision"))
        self.comboModeDecision.setToolTip(_translate("MainWindow", "Binaire : 0 ou 1 ambulance par site\n"
"Entier : nombre quelconque d\'ambulances par site"))
        self.comboModeDecision.setItemText(0, _translate("MainWindow", "🔘 Binaire (Installer ou Non)"))
        self.comboModeDecision.setItemText(1, _translate("MainWindow", "🔢 Entier (Nombre d\'Ambulances)"))
        self.labelTotalAmb.setText(_translate("MainWindow", "🚑 Total d\'Ambulances :"))
        self.labelTotalAmb.setToolTip(_translate("MainWindow", "Budget total d\'ambulances disponibles"))
        self.spinTotalAmbulances.setToolTip(_translate("MainWindow", "Nombre total d\'ambulances à placer"))
        self.labelMaxDist.setText(_translate("MainWindow", "Distance Max de Couverture (km) :"))
        self.labelMaxDist.setToolTip(_translate("MainWindow", "Distance maximale pour qu\'une ambulance puisse couvrir une zone"))
        self.spinMaxDistance.setToolTip(_translate("MainWindow", "Rayon de couverture en kilomètres"))
        self.btnOptimize.setText(_translate("MainWindow", "LANCER L\'OPTIMISATION"))
        self.btnOptimize.setToolTip(_translate("MainWindow", "Cliquez pour calculer le placement optimal des ambulances"))
        self.groupResults.setTitle(_translate("MainWindow", "Résultats de l\'Optimisation"))
        self.textResults.setPlaceholderText(_translate("MainWindow", "Les résultats de l\'optimisation s\'afficheront ici..."))
